# Generated by Django 3.0.3 on 2020-04-02 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0002_sub_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sub_Category',
            new_name='SubCategory',
        ),
    ]
